<%@ page import="java.sql.*" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<%
    Class.forName("com.mysql.jdbc.Driver");
    String url = "jdbc:mysql://localhost:3306/testjsp";
    String user = "root";
    String password = "";
    Connection conn = DriverManager.getConnection(url, user, password);
    Statement stmt = conn.createStatement();
    ResultSet rs = stmt.executeQuery("SELECT COUNT(*) AS total_orders, SUM(quantity * unit_price) AS total_revenue FROM orders");
    rs.next();
    int total_orders = rs.getInt("total_orders");
    double total_revenue = rs.getDouble("total_revenue");
    double average_order_value = total_revenue / total_orders;
%>
<table>
    <tr>
        <th>Total number of orders</th>
        <td><%= total_orders %></td>
    </tr>
    <tr>
        <th>Total revenue generated by all orders</th>
        <td><%= total_revenue %></td>
    </tr>
    <tr>
        <th>Average order value</th>
        <td><%= average_order_value %></td>
    </tr>
</table>
